on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      DISCORD_WEBHOOK: 'https://discord.com/api/webhooks/1077696082781409290/z12vqgUZIvtq8fbfxp-WGAa8Ytal9hRV5Cy_QKT1hjIwRy6Ak_7HK3O2UxYkVSfr6m1_'
      REPOSITORY: ${{ toJSON(github.event.repository) }}
      COMMITS: ${{ toJSON(github.event.commits) }}
      HEAD_COMMIT: ${{ toJSON(github.event.head_commit) }}
    steps:
      - name: Send message to discord
        id: hello
        uses: driccio98/git-2-discord@v1.2
      - name: Get the output time
        run: echo "The commits are ${{ steps.hello.outputs.time }}"
