on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      COMMITS: ${{ toJSON(github.event.commits) }}
    steps:
      - name: Hello world action step
        id: hello
        uses: driccio98/git-2-discord@v2.1
      - name: Get the output time
        run: echo "The commits are ${{ steps.hello.outputs.time }}"
