on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: driccio98/git-2-discord@v1.4
        with:
          commits: ${{github.event.commits}}
      - name: Get the output time
        run: echo "The commits are ${{ steps.hello.outputs.time }}"
